// <auto-generated />
using System;
using ChurchProjection.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChurchProjection.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectionDbContext))]
    [Migration("20260821145103_Fts5Search")]
    partial class Fts5Search
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ChurchProjection.Domain.Library.MediaItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Domain.Library.Song", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("Ccli")
                        .HasColumnType("TEXT")
                        .HasColumnName("ccli");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Domain.Library.Translation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Abbrev")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("abbrev");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("translations", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Domain.Library.Verse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("book_id");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chapter");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("verse");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("TranslationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("translation_id");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId", "BookId", "Chapter", "Number")
                        .IsUnique();

                    b.ToTable("verses", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Domain.Services.ServicePlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_date");

                    b.HasKey("Id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Infrastructure.Persistence.BookNameRow", b =>
                {
                    b.Property<string>("TranslationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("translation_id");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("book_id");

                    b.Property<string>("Abbrev")
                        .HasColumnType("TEXT")
                        .HasColumnName("abbrev");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("TranslationId", "BookId");

                    b.ToTable("book_names", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Infrastructure.Persistence.LiveStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Blackout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blackout");

                    b.Property<string>("LiveItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("live_item_id");

                    b.Property<bool>("LiveMediaAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("live_media_available");

                    b.Property<int>("LivePageIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("live_page_index");

                    b.Property<string>("PreviewItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_item_id");

                    b.Property<bool>("PreviewMediaAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preview_media_available");

                    b.Property<int>("PreviewPageIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preview_page_index");

                    b.Property<string>("ServiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.Property<string>("SkippedJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("skipped_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("live_state", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Infrastructure.Persistence.SettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("ChurchProjection.Domain.Library.Song", b =>
                {
                    b.OwnsMany("ChurchProjection.Domain.Library.SongPage", "Pages", b1 =>
                        {
                            b1.Property<string>("song_id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Position")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("position");

                            b1.Property<string>("SectionLabel")
                                .HasColumnType("TEXT")
                                .HasColumnName("section_label");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("text");

                            b1.HasKey("song_id", "Position");

                            b1.ToTable("song_pages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("song_id");
                        });

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("ChurchProjection.Domain.Services.ServicePlan", b =>
                {
                    b.OwnsMany("ChurchProjection.Domain.Services.ServiceItem", "Items", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("kind");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("label");

                            b1.Property<int>("Position")
                                .HasColumnType("INTEGER")
                                .HasColumnName("position");

                            b1.Property<string>("Ref")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ref_json");

                            b1.Property<string>("service_id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("service_id");

                            b1.ToTable("service_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
